Test ng hw
nastassia0202/Lesson_6 pull request #5
Opened 2022-01-16 20:18 UTC by nastassia0202

2022-01-17 12:31 UTC, wildpioneer commented
В репозиторий добавлены файлы из папки target - чего делать нельзя

2022-01-17 12:32 UTC, wildpioneer requested changes

2022-01-17 12:32 UTC, wildpioneer commented on src/test/java/tests/DifferenceTest.java
> +    }
Отсутствует тест на проверки деления на 0

2022-01-17 12:32 UTC, wildpioneer commented on src/test/java/tests/DivisionTest.java
> +        Assert.assertTrue(calculator.div(15, 3) == 5);
В проверки лучше добавлять поясняющий текст

2022-01-23 18:15 UTC, nastassia0202 commented on src/test/java/tests/DifferenceTest.java
> +    }
Исправлено!

2022-01-23 18:15 UTC, nastassia0202 commented on src/test/java/tests/DivisionTest.java
> +        Assert.assertTrue(calculator.div(15, 3) == 5);
Исправлено!

2022-01-31 11:52 UTC, wildpioneer commented
Проверено

2022-01-31 11:52 UTC, closed without merging